# Generated by Django 5.1.4 on 2024-12-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Профиль", "verbose_name_plural": "Пользователии"},
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="id_question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="commentanswer",
            old_name="id_answer",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="likesanswer",
            old_name="id_answer",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="likescomment",
            old_name="id_comment",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="id_category",
            new_name="category",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="id_user_answer",
        ),
        migrations.RemoveField(
            model_name="commentanswer",
            name="id_user",
        ),
        migrations.RemoveField(
            model_name="likesanswer",
            name="id_user",
        ),
        migrations.RemoveField(
            model_name="likescomment",
            name="id_user",
        ),
        migrations.RemoveField(
            model_name="question",
            name="id_user",
        ),
        migrations.AddField(
            model_name="answer",
            name="user_answer",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commentanswer",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="likesanswer",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="likescomment",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.profile",
            ),
            preserve_default=False,
        ),
    ]
