# Generated by Django 5.1.4 on 2025-01-08 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_alter_answer_answer_body_alter_answer_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprofileaccount",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="profileAccount",
        ),
        migrations.AlterField(
            model_name="historicalquestion",
            name="question_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name="HistoricalprofileAccount",
        ),
    ]
