# Generated by Django 5.1.4 on 2025-01-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_historicalprofileaccount_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-question_date'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
